### ISSUE TITLE
How to work with the instrument correctly?

### ISSUE THREAD

**Issue by djzlorb** [Fa-b/D2Animations#1]
When uploading 1 file or multiple files i get the following message (chrome 86.0.4240.193)

```
Your browser seems to not support some features.

SyntaxError: Failed to execute 'postMessage' on 'Window': Invalid target origin 'null' in a call to 'postMessage'.:

Error: Failed to execute 'postMessage' on 'Window': Invalid target origin 'null' in a call to 'postMessage'. at setImmediate (file:///D:/Games/DDG/Site/ItemScreenshot/Tools/D2Animations/js/JSThread.js:24:11) at file:///D:/Games/DDG/Site/ItemScreenshot/Tools/D2Animations/js/JSThread.js:56:56 at new Promise () at file:///D:/Games/DDG/Site/ItemScreenshot/Tools/D2Animations/js/JSThread.js:56:23 at HTMLInputElement.mountFiles (file:///D:/Games/DDG/Site/ItemScreenshot/Tools/D2Animations/js/file.js:161:25)
```

**Comment by Fa-b** [comment]
[here](https://github.com/Fa-b/D2Animations/blob/27450ca09e670a13e283a7ff35e1cea0492b5a0f/js/JSThread.js#L24) replace the line with:
```js
window.postMessage({fid}, "*");
```
The reason you are seeing this error is because you are running the site from your filesystem.

**Comment by Fa-b** [comment]
solved
